# Generated by Django 6.0.1 on 2026-01-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(default='', max_length=50)),
                ('img_first', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('img_second', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('img_third', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('service_link', models.URLField(blank=True)),
                ('service_insta', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_url', models.URLField(default='')),
                ('img_src', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('description', models.CharField(default='', max_length=200)),
                ('item_name', models.CharField(default='', max_length=50)),
                ('item_category', models.CharField(default='', max_length=50)),
                ('item_price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('href', models.URLField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bmflower.about')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_choice', models.CharField(choices=[('text', 'Text'), ('link', 'Link')], max_length=10)),
                ('content', models.TextField()),
                ('href', models.URLField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='bmflower.about')),
            ],
        ),
    ]
